#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Raises a NameError"""
    raise NameError(message)  # Retourne une exception NameError
